services:
  postgres:
    image: postgres:15
    container_name: amdemu-postgres
    environment:
      POSTGRES_USER: amdemu
      POSTGRES_DB: amdemu_db
      POSTGRES_HOST_AUTH_METHOD: trust   # <--- THIS IS KEY
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
